In [37]:
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt #plotting
import seaborn as sns #graphical representation

In [2]:
df = pd.read_csv('test.csv')

In [3]:
df.head()

,Unnamed: 0,Contact,Email,Business Type,Budget,Starting Date,End Date,Response,RM
0,KUNAL ROY,9827328551,Yorkunal4@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN
1,Ojha Kshitiz,9848617751,NaN,Mobile shop,NaN,NaN,NaN,not interested in advertising,NaN
2,Santosh Upadhyay,9856037823,NaN,General,NaN,NaN,NaN,must contact in viber,NaN
3,Pradeep Dhakal,9841581150,NaN,Montessori,NaN,NaN,NaN,want to start the advertisement,NaN
4,Suresh Sudik Garagain,9840015215,NaN,NaN,NaN,NaN,NaN,number not available 9th april 3:00,NaN

In [4]:
df.drop(['Budget', 'Starting Date', 'End Date','RM','Email'], axis=1, inplace=True)

In [5]:
df

,Unnamed: 0,Contact,Business Type,Response
0,KUNAL ROY,9827328551,NaN,NaN
1,Ojha Kshitiz,9848617751,Mobile shop,not interested in advertising
2,Santosh Upadhyay,9856037823,General,must contact in viber
3,Pradeep Dhakal,9841581150,Montessori,want to start the advertisement
4,Suresh Sudik Garagain,9840015215,NaN,number not available 9th april 3:00
5,Bibhash Ambrose Mallik,9817849121,NaN,not recieve call 9th april
6,Vivek,9857030993,NaN,not recieve call 9th april
7,BP subedi,9841825504,NaN,call not recieved
8,Sabin Chamling Ssg,9813889611,"photo studio & hotel (jhapa, damak)",not reachable
9,Deepak Shah,9815225450,Hardware suppliers,viber all details or whatsapp
10,Rk Shrestha,9841281841,Dish Home,requested for customer number basis
11,Manish Bharrari,9824047768,NaN,NaN
12,Chesang Lama,9851208011,Parlour,need to follow up
13,Shree Krishna Rijal,9851933395,NaN,not reachable
14,J.D. corier and cargo srvice,9849339439,NaN,NaN
15,Sagar Raj Khadka,9860466387,Thanka,more interested and visit office
16,Saurab Raj Sharma,9841248997,Electronics (Surkhet),intereseted and call soon
17,Sarada Dana Udyog,9857050910,Animal Foods (Rupandehi),call when he is free
18,Everest hardware and suppliers (bishnu shrestha),9849601143,hardware and suppliers,call us when he is ready
19,Bhagirath Pokharel,9851075468,General,need to follow up
20,Horizen Prince,9818823499,NaN,need follow up 9th april 3:37
21,Suman Raj Nepal,9843934365,NaN,need follow up
22,Marich Man,9851162086,NaN,NaN
23,Sanam bk,9849470659,Steeping Stones,visit
24,Rupa Joshi Pradhan,9851192499,wholeseller and jewellery,interested and promise to visit office
25,Sushil Vajracharya,9841320766,General,promise a visit
26,Hari Prasad Aryal,9867424709,Kirana and Dairy,interested and provide time when ready
27,Sushil Parajuli,9862689249,online shoppings,Need to boost the facebook page immediately
28,Mohal Khatri,9845248672,mobile shop,NaN
29,Deepesh dahal maharjan,9860333198,Glass shop,call not recieved (22th april 3 pm)
...,...,...,...,...
483,bauwa hotel,9841808341,bauwa hotel and guest house,not received
484,kamal khanal,9801094800,Zenith Abroad Education Consultancy Pvt. Ltd,NaN
485,Gyanendra,9851133700,Edu Consultancy,Converted
486,gokul aryal,9841533850,himal sign,after 28 gate
487,gaurav,9843769634,unique art and sticker house,after4-5 days
488,balram wagle,9851206641,lulu media publication pvt ltd,Call by himself later
489,ichchha wagle,9851025344,hotel icchya,not interested
490,himal gyawali,9861696321,TMA travels,he will call
491,mahesh acharya,9851213007,global IT solution,sent proposal/follow up
492,naresh stha,9843622768,mini mart,follow up
493,pankaj jaiswal,9847087325,clinic,follow up
494,Sanjay Rauniyar,9779802016657,Clothing Store,need to verify page
495,Dinesh Kumar Bhagat,9855023495,Jagdamba Depo & Sales,sent proposal/follow up
496,Lalkesh Jaishi,9858421774,cosmetic and fitness,he will call
497,Shyam Krishna Shrestha,9852045059,NaN,not interested
498,Prem Thapa Magar,9805438044,clinic,boost interested/follow up by rosan dai
499,KR Kashyap,9851059864,handicraft,not interested
500,Ajay Chaudhary,9801650075,Maa janaki computer and electronics,will contact
501,Ramesh Shrestha,9860301286,sunglasses,will visit
502,Krishna Luitel Fish,:9741002642/9803514715,NaN,not interested
503,Rameshwor Basnet,"01-5177099, 9823530853",real state kind of businss,not interested
504,Anish Gautam,9851247812,restaurant,need to send proposal/follow up
505,Ramjee Dhakal,9851042462,restaurant,he will call
506,Prem Khadka,9851082695,NaN,call later
507,Santosh Gupta,9858027857,Advertising buisness,sent proposal/follow up
508,Er Probin Mahato,9854028398,distribution suppliers,he will inform later
509,Hari Saran Adhikari,9808870536,NaN,not interested
510,Prem Lama,9851043592,handicrafts,he will visit
511,Pashupati Parajuli Aviral,NaN,janta dairy and krishi farm pvt,sent proposal/follow up
512,Pancha Shrestha,9849861175,NaN,he will call

In [6]:
df['Contact'].describe()

count            501
unique           477
top       9854028398
freq               3
Name: Contact, dtype: object

In [7]:
df.aggregate('mean')

Series([], dtype: float64)

In [8]:
df

,Unnamed: 0,Contact,Business Type,Response
0,KUNAL ROY,9827328551,NaN,NaN
1,Ojha Kshitiz,9848617751,Mobile shop,not interested in advertising
2,Santosh Upadhyay,9856037823,General,must contact in viber
3,Pradeep Dhakal,9841581150,Montessori,want to start the advertisement
4,Suresh Sudik Garagain,9840015215,NaN,number not available 9th april 3:00
5,Bibhash Ambrose Mallik,9817849121,NaN,not recieve call 9th april
6,Vivek,9857030993,NaN,not recieve call 9th april
7,BP subedi,9841825504,NaN,call not recieved
8,Sabin Chamling Ssg,9813889611,"photo studio & hotel (jhapa, damak)",not reachable
9,Deepak Shah,9815225450,Hardware suppliers,viber all details or whatsapp
10,Rk Shrestha,9841281841,Dish Home,requested for customer number basis
11,Manish Bharrari,9824047768,NaN,NaN
12,Chesang Lama,9851208011,Parlour,need to follow up
13,Shree Krishna Rijal,9851933395,NaN,not reachable
14,J.D. corier and cargo srvice,9849339439,NaN,NaN
15,Sagar Raj Khadka,9860466387,Thanka,more interested and visit office
16,Saurab Raj Sharma,9841248997,Electronics (Surkhet),intereseted and call soon
17,Sarada Dana Udyog,9857050910,Animal Foods (Rupandehi),call when he is free
18,Everest hardware and suppliers (bishnu shrestha),9849601143,hardware and suppliers,call us when he is ready
19,Bhagirath Pokharel,9851075468,General,need to follow up
20,Horizen Prince,9818823499,NaN,need follow up 9th april 3:37
21,Suman Raj Nepal,9843934365,NaN,need follow up
22,Marich Man,9851162086,NaN,NaN
23,Sanam bk,9849470659,Steeping Stones,visit
24,Rupa Joshi Pradhan,9851192499,wholeseller and jewellery,interested and promise to visit office
25,Sushil Vajracharya,9841320766,General,promise a visit
26,Hari Prasad Aryal,9867424709,Kirana and Dairy,interested and provide time when ready
27,Sushil Parajuli,9862689249,online shoppings,Need to boost the facebook page immediately
28,Mohal Khatri,9845248672,mobile shop,NaN
29,Deepesh dahal maharjan,9860333198,Glass shop,call not recieved (22th april 3 pm)
...,...,...,...,...
483,bauwa hotel,9841808341,bauwa hotel and guest house,not received
484,kamal khanal,9801094800,Zenith Abroad Education Consultancy Pvt. Ltd,NaN
485,Gyanendra,9851133700,Edu Consultancy,Converted
486,gokul aryal,9841533850,himal sign,after 28 gate
487,gaurav,9843769634,unique art and sticker house,after4-5 days
488,balram wagle,9851206641,lulu media publication pvt ltd,Call by himself later
489,ichchha wagle,9851025344,hotel icchya,not interested
490,himal gyawali,9861696321,TMA travels,he will call
491,mahesh acharya,9851213007,global IT solution,sent proposal/follow up
492,naresh stha,9843622768,mini mart,follow up
493,pankaj jaiswal,9847087325,clinic,follow up
494,Sanjay Rauniyar,9779802016657,Clothing Store,need to verify page
495,Dinesh Kumar Bhagat,9855023495,Jagdamba Depo & Sales,sent proposal/follow up
496,Lalkesh Jaishi,9858421774,cosmetic and fitness,he will call
497,Shyam Krishna Shrestha,9852045059,NaN,not interested
498,Prem Thapa Magar,9805438044,clinic,boost interested/follow up by rosan dai
499,KR Kashyap,9851059864,handicraft,not interested
500,Ajay Chaudhary,9801650075,Maa janaki computer and electronics,will contact
501,Ramesh Shrestha,9860301286,sunglasses,will visit
502,Krishna Luitel Fish,:9741002642/9803514715,NaN,not interested
503,Rameshwor Basnet,"01-5177099, 9823530853",real state kind of businss,not interested
504,Anish Gautam,9851247812,restaurant,need to send proposal/follow up
505,Ramjee Dhakal,9851042462,restaurant,he will call
506,Prem Khadka,9851082695,NaN,call later
507,Santosh Gupta,9858027857,Advertising buisness,sent proposal/follow up
508,Er Probin Mahato,9854028398,distribution suppliers,he will inform later
509,Hari Saran Adhikari,9808870536,NaN,not interested
510,Prem Lama,9851043592,handicrafts,he will visit
511,Pashupati Parajuli Aviral,NaN,janta dairy and krishi farm pvt,sent proposal/follow up
512,Pancha Shrestha,9849861175,NaN,he will call

In [9]:
number=df['Contact']
ntcNumberUsers = []
ntcPattern=re.compile('98[4-6][0-9]{7}');
x=ntcPattern.match(number[1])
# print(type(x))
for i in range(0, number.size-1):
    if isinstance(number[i], str):
        result = ntcPattern.match(number[i])
        if result:
            ntcNumberUsers.append(number[i])
print(ntcNumberUsers)

['9848617751', '9856037823', '9841581150', '9840015215', '9857030993', '9841825504', '9841281841', '9851208011', '9851933395', '9849339439', '9860466387', '9841248997', '9857050910', '9849601143', '9851075468', '9843934365', '9851162086', '9849470659', '9851192499', '9841320766', '9867424709', '9862689249', '9845248672', '9860333198', '9857024717', '9851134620', '9849717982', '9857036752', '9851192614', '9856078100', '9855063855', '9864455516', '9867003304', '9841941007', '9849680813', '9841009879', '9851226464', '9860200278', '9851120796', '9841409269', '9851098080/ 9861929859', '9855069215', '9843766345', '9855077321', '9842059713', '9851192612', '9852849060', '9851033010', '9851148792', '9861726497', '9842056164', '9867926884', '9843866133', '9856051606', '9858024433/9857039492', '9851076384', '9860228122', '9841409988', '9852021345', '9865237020', '9851036067', '9861288843', '9856023690/9802523690', '9843688811', '9851023285', '9856039551', '9843212406', '9851168362', '9840432076', '9865680040', '9857052060', '9858059070', '9858422328', '9845545492', '9865237020', '9868100440 Rolpa', '9844074547', '9868084919', '9844918218', '9857061636', '9868084919', '9862689249', '9843745055', '9849291111', '9847764652', '9862037817', '9867877297', '9861790667', '9851198915', '9857031639', '9867926884', '9869578474', '9844016148', '9852053953', '9841709512', '9851076943/ 985108693', '9843271310', '9841025185', '9844825958', '9860778829', '9861630901', '9856036086', '9851206095', '9851195211', '9867415233', '9852674911', '9851089325', '9866735128', '9842932141', '9849402737', '9861946399', '9851066943', '9851008270', '9845358510', '9841601313', '9841688038', '9861054133', '9857030090', '9851179533', '9856027332', '9841572407', '9857050122', '9851247813', '9851090694', '9841642244', '9867296208', '9851088677', '9843693581', '9841518776', '9841667426', '9852051671', '9854026024', '9841433325', '9869393006', '9851078815', '9869556292', '9856035106', '9857660600', '9851170560', '9856010517', '9842934217', '9851179491', '9860902060', '9846013800', '9851234282', '9854037530', '9857844550', '9867003304', '9851123005', '9851015321', '9848834982', '9841401799', '9847272197', '9851134659', '9841859590', '9848997509', '9843572856', '9841091092', '9860120451', '9847661849', '9851115551', '9841595707', '9848968122', '9849406559', '9860620404', '9851123124', '9848064656', '9841676661', '9845030540', '9846532661', '9867717666', '9846532661', '9851142604', '9867801997', '9856015909', '9851012055', '9845674482', '9857024650', '9849239923', '9851210471', '9843096913', '9851053202', '9851185687', '9852023526', '9849291111', '9851061999', '9857824571', '9851054669', '9841021523', '9857834253', '9852672811', '9852022650', '9851043252', '9842755054', '9851033395', '9851206012', '9851225570', '9845556075', '9851061474', '9851117167', '9851039936', '9844711349', '9841270197', '9867233640', '9851073694', '9845517021', '9856060756', '9855082445', '9842639269', '9856060554', '9851001480', '9857822081', '9857625349', '9856045673', '9860638772', '9841570562', '9841570562', '9852042622', '9861790667', '9848457041', '9854028398', '9856072765', '9845086835', '9860723092', '9841523324', '9842629556', '9860389969', '9851095939', '9841725906', '9869537775', '9849845061', '9854028398', '9847160433', '9851033337', '9857623036', '9857036985', '9851095239', '9858027857', '9867144167', '9843808155', '9851107693', '9841465138', '9848457041', '9858027857', '9851151170', '9858021439', '9851166850', '9851011603', '9861315135', '9851007333', '9849041915', '9851078186', '9851008630', '9851079278', '9851107693', '9851055310', '9857032515', '9841558333', '9842430503', '9851044911', '9841869032', '9860313326', '9856053453', '9851019752', '9851045068', '9849281784', '9857058153', '9851033395', '9851034195', '9846516188', '9852057729', '9863314315', '9841205740', '9851170561', '9851232045,', '9851126243', '9857065264', '9841029159', '9840797133', '9841066322', '9851056728', '9851133700', '9841284232', '9841284232', '9849806292', '9851179573', '9851179526', '9841902076', '9851021697', '9849149159', '9851119626', '9842039001', '9841808341', '9851133700', '9841533850', '9843769634', '9851206641', '9851025344', '9861696321', '9851213007', '9843622768', '9847087325', '9855023495', '9858421774', '9852045059', '9851059864', '9860301286', '9851247812', '9851042462', '9851082695', '9858027857', '9854028398', '9851043592']

In [10]:
number=df['Contact']
ncellNumberUsers = []
ncellPattern=re.compile('98[0-2][0-9]{7}');
x=ncellPattern.match(number[1])
# print(type(x))
for i in range(0, number.size-1):
    if isinstance(number[i], str):
        result = ncellPattern.match(number[i])
        if result:
            ncellNumberUsers.append(number[i])
print(ncellNumberUsers)

['9827328551', '9817849121', '9813889611', '9815225450', '9824047768', '9818823499', '9806084570', '9823124428', '9803214417', '9808316261', '9823111400', '9818022176', '9813578641', '9823124428', '9811768300', '9819535180', '9801130517', '9818286993', '9816330452', '9811857865', '9818120465', '9817089004', '9813002656', '9810499852', '9815106523', '9803570760', '9817322509', '9804421677', '9818150380', '9813411101', '9801199382', '9800531112', '9816601801', '9818678187', '9824154162', '9811690191', '9824240807', '9815977433', '9812484045', '9808179539', '9801227342', '9800863045', '9818125762', '9823138067', '9811907322', '9824459323', '9824896800', '9801352147', '9801022314', '9814002095', '9813556300', '9826471623', '9816351081', '9804310192', '9816761489', '9805429360', '9822577006', '9800516682', '9818934022', '9808202019', '9803335455', '9805833257', '9817237825', '9824149213', '9808671751', '9816946992', '9813708149', '9802069798', '9801142224', '9808969093', '9819177656', '9813550646', '9818593195', '9808870536', '9808764879', '9801018277', '9803303262', '9802016657', '9818890373', '9810058974', '9823474650', '9811307386', '9818066404', '9825170774', '9802034080', '9807140669', '9801156565', '9823087012', '9808408611', '9817113539', '9803456726', '9814189416', '9801094800', '9814110611', '9823014684', '9801094800', '9803027890', '9804135499', '9801005300', '9824331068', '9817117593', '9818803682', '9808540732', '9802791247', '9801023327', '9817197943', '9823249898', '9816069777', '9816481887', '9813804645', '9803647605', '9823406069', '9802910012', '9801116110', '9817011456', '9813280432', '9823491268', '9807185695', '9804303621', '9808455575', '9814326597', '9812329672', '9803022100', '9816224862', '9806584195', '9807004757', '9821619343', '9813522726', '9824027576', '9804091664', '9824979190', '9815013761', '9813683838', '9823406069', '9823115305', '9801025289', '9801094800', '9805438044', '9801650075', '9808870536']

In [18]:
NTC= ['9848617751', '9856037823', '9841581150', '9840015215', '9857030993', '9841825504', '9841281841', '9851208011', '9851933395', '9849339439', '9860466387', '9841248997', '9857050910', '9849601143', '9851075468', '9843934365', '9851162086', '9849470659', '9851192499', '9841320766', '9867424709', '9862689249', '9845248672', '9860333198', '9857024717', '9851134620', '9849717982', '9857036752', '9851192614', '9856078100', '9855063855', '9864455516', '9867003304', '9841941007', '9849680813', '9841009879', '9851226464', '9860200278', '9851120796', '9841409269', '9851098080/ 9861929859', '9855069215', '9843766345', '9855077321', '9842059713', '9851192612', '9852849060', '9851033010', '9851148792', '9861726497', '9842056164', '9867926884', '9843866133', '9856051606', '9858024433/9857039492', '9851076384', '9860228122', '9841409988', '9852021345', '9865237020', '9851036067', '9861288843', '9856023690/9802523690', '9843688811', '9851023285', '9856039551', '9843212406', '9851168362', '9840432076', '9865680040', '9857052060', '9858059070', '9858422328', '9845545492', '9865237020', '9868100440 Rolpa', '9844074547', '9868084919', '9844918218', '9857061636', '9868084919', '9862689249', '9843745055', '9849291111', '9847764652', '9862037817', '9867877297', '9861790667', '9851198915', '9857031639', '9867926884', '9869578474', '9844016148', '9852053953', '9841709512', '9851076943/ 985108693', '9843271310', '9841025185', '9844825958', '9860778829', '9861630901', '9856036086', '9851206095', '9851195211', '9867415233', '9852674911', '9851089325', '9866735128', '9842932141', '9849402737', '9861946399', '9851066943', '9851008270', '9845358510', '9841601313', '9841688038', '9861054133', '9857030090', '9851179533', '9856027332', '9841572407', '9857050122', '9851247813', '9851090694', '9841642244', '9867296208', '9851088677', '9843693581', '9841518776', '9841667426', '9852051671', '9854026024', '9841433325', '9869393006', '9851078815', '9869556292', '9856035106', '9857660600', '9851170560', '9856010517', '9842934217', '9851179491', '9860902060', '9846013800', '9851234282', '9854037530', '9857844550', '9867003304', '9851123005', '9851015321', '9848834982', '9841401799', '9847272197', '9851134659', '9841859590', '9848997509', '9843572856', '9841091092', '9860120451', '9847661849', '9851115551', '9841595707', '9848968122', '9849406559', '9860620404', '9851123124', '9848064656', '9841676661', '9845030540', '9846532661', '9867717666', '9846532661', '9851142604', '9867801997', '9856015909', '9851012055', '9845674482', '9857024650', '9849239923', '9851210471', '9843096913', '9851053202', '9851185687', '9852023526', '9849291111', '9851061999', '9857824571', '9851054669', '9841021523', '9857834253', '9852672811', '9852022650', '9851043252', '9842755054', '9851033395', '9851206012', '9851225570', '9845556075', '9851061474', '9851117167', '9851039936', '9844711349', '9841270197', '9867233640', '9851073694', '9845517021', '9856060756', '9855082445', '9842639269', '9856060554', '9851001480', '9857822081', '9857625349', '9856045673', '9860638772', '9841570562', '9841570562', '9852042622', '9861790667', '9848457041', '9854028398', '9856072765', '9845086835', '9860723092', '9841523324', '9842629556', '9860389969', '9851095939', '9841725906', '9869537775', '9849845061', '9854028398', '9847160433', '9851033337', '9857623036', '9857036985', '9851095239', '9858027857', '9867144167', '9843808155', '9851107693', '9841465138', '9848457041', '9858027857', '9851151170', '9858021439', '9851166850', '9851011603', '9861315135', '9851007333', '9849041915', '9851078186', '9851008630', '9851079278', '9851107693', '9851055310', '9857032515', '9841558333', '9842430503', '9851044911', '9841869032', '9860313326', '9856053453', '9851019752', '9851045068', '9849281784', '9857058153', '9851033395', '9851034195', '9846516188', '9852057729', '9863314315', '9841205740', '9851170561', '9851232045,', '9851126243', '9857065264', '9841029159', '9840797133', '9841066322', '9851056728', '9851133700', '9841284232', '9841284232', '9849806292', '9851179573', '9851179526', '9841902076', '9851021697', '9849149159', '9851119626', '9842039001', '9841808341', '9851133700', '9841533850', '9843769634', '9851206641', '9851025344', '9861696321', '9851213007', '9843622768', '9847087325', '9855023495', '9858421774', '9852045059', '9851059864', '9860301286', '9851247812', '9851042462', '9851082695', '9858027857', '9854028398', '9851043592']

NCell=['9827328551', '9817849121', '9813889611', '9815225450', '9824047768', '9818823499', '9806084570', '9823124428', '9803214417', '9808316261', '9823111400', '9818022176', '9813578641', '9823124428', '9811768300', '9819535180', '9801130517', '9818286993', '9816330452', '9811857865', '9818120465', '9817089004', '9813002656', '9810499852', '9815106523', '9803570760', '9817322509', '9804421677', '9818150380', '9813411101', '9801199382', '9800531112', '9816601801', '9818678187', '9824154162', '9811690191', '9824240807', '9815977433', '9812484045', '9808179539', '9801227342', '9800863045', '9818125762', '9823138067', '9811907322', '9824459323', '9824896800', '9801352147', '9801022314', '9814002095', '9813556300', '9826471623', '9816351081', '9804310192', '9816761489', '9805429360', '9822577006', '9800516682', '9818934022', '9808202019', '9803335455', '9805833257', '9817237825', '9824149213', '9808671751', '9816946992', '9813708149', '9802069798', '9801142224', '9808969093', '9819177656', '9813550646', '9818593195', '9808870536', '9808764879', '9801018277', '9803303262', '9802016657', '9818890373', '9810058974', '9823474650', '9811307386', '9818066404', '9825170774', '9802034080', '9807140669', '9801156565', '9823087012', '9808408611', '9817113539', '9803456726', '9814189416', '9801094800', '9814110611', '9823014684', '9801094800', '9803027890', '9804135499', '9801005300', '9824331068', '9817117593', '9818803682', '9808540732', '9802791247', '9801023327', '9817197943', '9823249898', '9816069777', '9816481887', '9813804645', '9803647605', '9823406069', '9802910012', '9801116110', '9817011456', '9813280432', '9823491268', '9807185695', '9804303621', '9808455575', '9814326597', '9812329672', '9803022100', '9816224862', '9806584195', '9807004757', '9821619343', '9813522726', '9824027576', '9804091664', '9824979190', '9815013761', '9813683838', '9823406069', '9823115305', '9801025289', '9801094800', '9805438044', '9801650075', '9808870536']

,Unnamed: 0,Contact,Business Type,Response
0,KUNAL ROY,9827328551,NaN,NaN
1,Ojha Kshitiz,9848617751,Mobile shop,not interested in advertising
2,Santosh Upadhyay,9856037823,General,must contact in viber
3,Pradeep Dhakal,9841581150,Montessori,want to start the advertisement
4,Suresh Sudik Garagain,9840015215,NaN,number not available 9th april 3:00
5,Bibhash Ambrose Mallik,9817849121,NaN,not recieve call 9th april
6,Vivek,9857030993,NaN,not recieve call 9th april
7,BP subedi,9841825504,NaN,call not recieved
8,Sabin Chamling Ssg,9813889611,"photo studio & hotel (jhapa, damak)",not reachable
9,Deepak Shah,9815225450,Hardware suppliers,viber all details or whatsapp
10,Rk Shrestha,9841281841,Dish Home,requested for customer number basis
11,Manish Bharrari,9824047768,NaN,NaN
12,Chesang Lama,9851208011,Parlour,need to follow up
13,Shree Krishna Rijal,9851933395,NaN,not reachable
14,J.D. corier and cargo srvice,9849339439,NaN,NaN
15,Sagar Raj Khadka,9860466387,Thanka,more interested and visit office
16,Saurab Raj Sharma,9841248997,Electronics (Surkhet),intereseted and call soon
17,Sarada Dana Udyog,9857050910,Animal Foods (Rupandehi),call when he is free
18,Everest hardware and suppliers (bishnu shrestha),9849601143,hardware and suppliers,call us when he is ready
19,Bhagirath Pokharel,9851075468,General,need to follow up
20,Horizen Prince,9818823499,NaN,need follow up 9th april 3:37
21,Suman Raj Nepal,9843934365,NaN,need follow up
22,Marich Man,9851162086,NaN,NaN
23,Sanam bk,9849470659,Steeping Stones,visit
24,Rupa Joshi Pradhan,9851192499,wholeseller and jewellery,interested and promise to visit office
25,Sushil Vajracharya,9841320766,General,promise a visit
26,Hari Prasad Aryal,9867424709,Kirana and Dairy,interested and provide time when ready
27,Sushil Parajuli,9862689249,online shoppings,Need to boost the facebook page immediately
28,Mohal Khatri,9845248672,mobile shop,NaN
29,Deepesh dahal maharjan,9860333198,Glass shop,call not recieved (22th april 3 pm)
...,...,...,...,...
483,bauwa hotel,9841808341,bauwa hotel and guest house,not received
484,kamal khanal,9801094800,Zenith Abroad Education Consultancy Pvt. Ltd,NaN
485,Gyanendra,9851133700,Edu Consultancy,Converted
486,gokul aryal,9841533850,himal sign,after 28 gate
487,gaurav,9843769634,unique art and sticker house,after4-5 days
488,balram wagle,9851206641,lulu media publication pvt ltd,Call by himself later
489,ichchha wagle,9851025344,hotel icchya,not interested
490,himal gyawali,9861696321,TMA travels,he will call
491,mahesh acharya,9851213007,global IT solution,sent proposal/follow up
492,naresh stha,9843622768,mini mart,follow up
493,pankaj jaiswal,9847087325,clinic,follow up
494,Sanjay Rauniyar,9779802016657,Clothing Store,need to verify page
495,Dinesh Kumar Bhagat,9855023495,Jagdamba Depo & Sales,sent proposal/follow up
496,Lalkesh Jaishi,9858421774,cosmetic and fitness,he will call
497,Shyam Krishna Shrestha,9852045059,NaN,not interested
498,Prem Thapa Magar,9805438044,clinic,boost interested/follow up by rosan dai
499,KR Kashyap,9851059864,handicraft,not interested
500,Ajay Chaudhary,9801650075,Maa janaki computer and electronics,will contact
501,Ramesh Shrestha,9860301286,sunglasses,will visit
502,Krishna Luitel Fish,:9741002642/9803514715,NaN,not interested
503,Rameshwor Basnet,"01-5177099, 9823530853",real state kind of businss,not interested
504,Anish Gautam,9851247812,restaurant,need to send proposal/follow up
505,Ramjee Dhakal,9851042462,restaurant,he will call
506,Prem Khadka,9851082695,NaN,call later
507,Santosh Gupta,9858027857,Advertising buisness,sent proposal/follow up
508,Er Probin Mahato,9854028398,distribution suppliers,he will inform later
509,Hari Saran Adhikari,9808870536,NaN,not interested
510,Prem Lama,9851043592,handicrafts,he will visit
511,Pashupati Parajuli Aviral,NaN,janta dairy and krishi farm pvt,sent proposal/follow up
512,Pancha Shrestha,9849861175,NaN,he will call

In [24]:
df['Telecom']=df['Contact']
df.head()

,Unnamed: 0,Contact,Business Type,Response,Telecom
0,KUNAL ROY,9827328551,NaN,NaN,9827328551
1,Ojha Kshitiz,9848617751,Mobile shop,not interested in advertising,9848617751
2,Santosh Upadhyay,9856037823,General,must contact in viber,9856037823
3,Pradeep Dhakal,9841581150,Montessori,want to start the advertisement,9841581150
4,Suresh Sudik Garagain,9840015215,NaN,number not available 9th april 3:00,9840015215

In [27]:
for (row, col) in df.iterrows():
    if (col.Telecom) in NTC:
        df['Telecom'].replace(to_replace=col.Telecom, value='NTC', inplace=True)
    if (col.Telecom) in NCell:
        df['Telecom'].replace(to_replace=col.Telecom, value='NCell', inplace=True)

In [28]:
df.head()

,Unnamed: 0,Contact,Business Type,Response,Telecom
0,KUNAL ROY,9827328551,NaN,NaN,NCell
1,Ojha Kshitiz,9848617751,Mobile shop,not interested in advertising,NTC
2,Santosh Upadhyay,9856037823,General,must contact in viber,NTC
3,Pradeep Dhakal,9841581150,Montessori,want to start the advertisement,NTC
4,Suresh Sudik Garagain,9840015215,NaN,number not available 9th april 3:00,NTC

In [29]:
df.groupby('Telecom')

In [42]:
Ncelldf=df[df['Telecom'] == 'NCell']
Ncelldf.head()

,Unnamed: 0,Contact,Business Type,Response,Telecom
0,KUNAL ROY,9827328551,NaN,NaN,NCell
5,Bibhash Ambrose Mallik,9817849121,NaN,not recieve call 9th april,NCell
8,Sabin Chamling Ssg,9813889611,"photo studio & hotel (jhapa, damak)",not reachable,NCell
9,Deepak Shah,9815225450,Hardware suppliers,viber all details or whatsapp,NCell
11,Manish Bharrari,9824047768,NaN,NaN,NCell

In [43]:
ncellnumber = Ncelldf.to_excel (r'C:\Users\sampa\OneDrive\Desktop\Sampanna\resources\ncellnumber.xlsx', index = None, header=True) #Don't forget to add '.xlsx' at the end of the path

print (Ncelldf)

                   Unnamed: 0     Contact  \
0                   KUNAL ROY  9827328551
5      Bibhash Ambrose Mallik  9817849121
8          Sabin Chamling Ssg  9813889611
9                 Deepak Shah  9815225450
11            Manish Bharrari  9824047768
20             Horizen Prince  9818823499
31              Utsav Bastola  9806084570
35     Manandhar Pathak Luxmi  9823124428
38                 Atit Magar  9803214417
40         Ashok Tamang theng  9808316261
48                     OTs PL  9823111400
52                Miwang Dong  9818022176
53         Anup Lingden Limbu  9813578641
55     Luxmi Pathak Manandhar  9823124428
56             Proobeen Kumar  9811768300
57        Street aryan kausal  9819535180
59           Ram baral Mandal  9801130517
66           Bikash prajapati  9818286993
67            Dhirendra Gupta  9816330452
69         Anwarul hak Ansari  9811857865
71              Deepesh Shahi  9818120465
72                 Tej Bohora  9817089004
75                Abinas lama  9813002656
80                Sajan Thapa  9810499852
84             Sailent Hunter  9815106523
90             Suman Bajagain  9803570760
97              Shamshad Aadi  9817322509
98              Alan Shrestha  9804421677
106                Shaan Shan  9818150380
110             Sujal Lopchan  9813411101
..                        ...         ...
378    Bishnu Ghimire Pragati  9803647605
383           Laxman Shrestha  9823406069
385           Dipendra Sunwar  9802910012
386               Ravin Thapa  9801116110
392  Designersantoshi Pokhrel  9817011456
400                Norbu lama  9813280432
401             Yagya Lamkade  9823491268
403               Raj Sapkota  9807185695
415     Indra Shah Insearcher  9804303621
416              Adhikari Raj  9808455575
420            chamling kiran  9814326597
423     unknown (bikesh  bro)  9812329672
425            Gopal Shrestha  9803022100
428        Sushil kumar swami  9816224862
431              Unil Thakuri  9806584195
435      Bipin Subba Ingwaram  9807004757
437               Manish Shah  9821619343
443     Prakash Tmg Syano Vai  9813522726
446           Surendra Khanal  9824027576
454                 Banty Sah  9804091664
456                   Unknown  9824979190
467             Dipak Ghimire  9815013761
468                Prem K Pun  9813683838
471           Laxman Shrestha  9823406069
472            Milan Mina Rai  9823115305
474         Rajesh trade link  9801025289
484              kamal khanal  9801094800
498          Prem Thapa Magar  9805438044
500            Ajay Chaudhary  9801650075
509       Hari Saran Adhikari  9808870536

                                      Business Type  \
0                                               NaN
5                                               NaN
8               photo studio & hotel (jhapa, damak)
9                                Hardware suppliers
11                                              NaN
20                                              NaN
31                     Electronics (surunga, jhapa)
35                                              NaN
38                                         Hardware
40                                              NaN
48                                  online business
52                                              NaN
53                         Olive and Basil Food Hub
55                                              NaN
56                                          Garage
57                  photography and online business
59                                       small shop
66                                              NaN
67                                              NaN
69                                              NaN
71                                              NaN
72                                              NaN
75                                              NaN
80                                              NaN
84                                              NaN
90                                              NaN
97                                              NaN
98                                              NaN
106  Sharwan Trades New chowk Choharwa Siraha Nepal
110                                     Gents fancy
..                                              ...
378                                             NaN
383                                             gas
385                                        adveture
386                                       advertise
392                                             NaN
400                                             NaN
401                                    kirana pasal
403                                      Restaurant
415              advertise for teachers requirement
416                                             NaN
420                         national life insurance
423                                             NaN
425                                             NaN
428                              mobile repair shop
431            FAST AND FURIOUS AUTO SERVICE CENTER
435            Hotel, Travel agency, Money transfer
437                                      Restaurant
443                                             NaN
446                                 training centre
454                                             NaN
456               Pathivara Hardware,puspalal chowk
467                            Electronics electric
468                                             NaN
471                                             Gas
472                                       advertise
474                                             NaN
484    Zenith Abroad Education Consultancy Pvt. Ltd
498                                          clinic
500             Maa janaki computer and electronics
509                                             NaN

                                              Response Telecom
0                                                  NaN   NCell
5                           not recieve call 9th april   NCell
8                                        not reachable   NCell
9                        viber all details or whatsapp   NCell
11                                                 NaN   NCell
20                       need follow up 9th april 3:37   NCell
31                               call when he is ready   NCell
35                      contact later when he is ready   NCell
38                interested and call when he is ready   NCell
40                                                 NaN   NCell
48                                     call by himself   NCell
52                                                 NaN   NCell
53                    send requirement untill tomorrow   NCell
55                                                 NaN   NCell
56                 Not availble and contact when ready   NCell
57                                         interested    NCell
59                                comes after 1 months   NCell
66   satisfied with our service and need to boost n...   NCell
67                          need to follow up tomorrow   NCell
69                      interested and call when ready   NCell
71                                 follow up tommorrow   NCell
72                                 follow up tommorrow   NCell
75                                   number switch off   NCell
80                                number not available   NCell
84                                                 NaN   NCell
90                                                 NaN   NCell
97                                                 NaN   NCell
98                                                 NaN   NCell
106                                                NaN   NCell
110                                                NaN   NCell
..                                                 ...     ...
378                                                NaN   NCell
383                                       folllowed up   NCell
385                                      proposal sent   NCell
386                                         interested   NCell
392                                                      NCell
400                                                NaN   NCell
401                                     not interested   NCell
403                        visit office when available   NCell
415                                     not interested   NCell
416                                        interersted   NCell
420                                                NaN   NCell
423                                  need to follow up   NCell
425                       he will visit office shortly   NCell
428                             office visit this week   NCell
431                             interested in boosting   NCell
435                                      not reachable   NCell
437                                  need to follow up   NCell
443                                                NaN   NCell
446                             interested in boosting   NCell
454                               Number not available   NCell
456                                 phone not Recieved   NCell
467                                       not received   NCell
468                                       not received   NCell
471                                      not reachable   NCell
472                                       not received   NCell
474                                                NaN   NCell
484                                                NaN   NCell
498            boost interested/follow up by rosan dai   NCell
500                                      will contact    NCell
509                                     not interested   NCell

[140 rows x 5 columns]

In [44]:
ntcnumberdf=df[df['Telecom'] == 'NTC']
ntcnumberdf.head()

,Unnamed: 0,Contact,Business Type,Response,Telecom
1,Ojha Kshitiz,9848617751,Mobile shop,not interested in advertising,NTC
2,Santosh Upadhyay,9856037823,General,must contact in viber,NTC
3,Pradeep Dhakal,9841581150,Montessori,want to start the advertisement,NTC
4,Suresh Sudik Garagain,9840015215,NaN,number not available 9th april 3:00,NTC
6,Vivek,9857030993,NaN,not recieve call 9th april,NTC

In [45]:
ntcnumber = ntcnumberdf.to_excel (r'C:\Users\sampa\OneDrive\Desktop\Sampanna\resources\ntcnumber.xlsx', index = None, header=True) #Don't forget to add '.xlsx' at the end of the path

print (ntcnumberdf)

                                           Unnamed: 0     Contact  \
1                                        Ojha Kshitiz  9848617751
2                                    Santosh Upadhyay  9856037823
3                                      Pradeep Dhakal  9841581150
4                               Suresh Sudik Garagain  9840015215
6                                               Vivek  9857030993
7                                           BP subedi  9841825504
10                                        Rk Shrestha  9841281841
12                                       Chesang Lama  9851208011
13                                Shree Krishna Rijal  9851933395
14                       J.D. corier and cargo srvice  9849339439
15                                   Sagar Raj Khadka  9860466387
16                                  Saurab Raj Sharma  9841248997
17                                  Sarada Dana Udyog  9857050910
18   Everest hardware and suppliers (bishnu shrestha)  9849601143
19                                 Bhagirath Pokharel  9851075468
21                                    Suman Raj Nepal  9843934365
22                                         Marich Man  9851162086
23                                           Sanam bk  9849470659
24                                 Rupa Joshi Pradhan  9851192499
25                                 Sushil Vajracharya  9841320766
26                                  Hari Prasad Aryal  9867424709
27                                    Sushil Parajuli  9862689249
28                                       Mohal Khatri  9845248672
29                             Deepesh dahal maharjan  9860333198
30                                   Mukun G. Kashyap  9857024717
32                                    Vijay Adhhikari  9851134620
33                                     Acesh Shrestha  9849717982
34                                     pradip ghimire  9857036752
36                                     Prajit Bashyal  9851192614
37                                       Buddi Sharma  9856078100
..                                                ...         ...
469                                           unknown  9841284232
470                                     Sushil Bhatta  9849806292
475                                    pramod  satyal  9851179573
476                                   subesh shrestha  9851179526
477                                      pradip dotel  9841902076
478                                    shankar pandey  9851021697
479                                   chandra neupane  9849149159
480                               purshottam bhattrai  9851119626
482                                 jitendra rumadali  9842039001
483                                       bauwa hotel  9841808341
485                                         Gyanendra  9851133700
486                                       gokul aryal  9841533850
487                                            gaurav  9843769634
488                                      balram wagle  9851206641
489                                     ichchha wagle  9851025344
490                                     himal gyawali  9861696321
491                                    mahesh acharya  9851213007
492                                       naresh stha  9843622768
493                                    pankaj jaiswal  9847087325
495                               Dinesh Kumar Bhagat  9855023495
496                                    Lalkesh Jaishi  9858421774
497                            Shyam Krishna Shrestha  9852045059
499                                        KR Kashyap  9851059864
501                                   Ramesh Shrestha  9860301286
504                                      Anish Gautam  9851247812
505                                     Ramjee Dhakal  9851042462
506                                       Prem Khadka  9851082695
507                                     Santosh Gupta  9858027857
508                                  Er Probin Mahato  9854028398
510                                         Prem Lama  9851043592

                          Business Type  \
1                           Mobile shop
2                               General
3                            Montessori
4                                   NaN
6                                   NaN
7                                   NaN
10                            Dish Home
12                              Parlour
13                                  NaN
14                                  NaN
15                               Thanka
16                Electronics (Surkhet)
17             Animal Foods (Rupandehi)
18               hardware and suppliers
19                              General
21                                  NaN
22                                  NaN
23                      Steeping Stones
24            wholeseller and jewellery
25                              General
26                     Kirana and Dairy
27                     online shoppings
28                          mobile shop
29                           Glass shop
30    plywood and textiles (lokanthali)
32                         perfume shop
33                cafe and food service
34               supa deurali computers
36                 Software development
37                 Hotel and restaurant
..                                  ...
469                          Agricultar
470                                 NaN
475              global training center
476         nepal college of management
477           all in one solar solution
478  three brothers home service center
479          university academic center
480      perfection enterprises pvt ltd
482            bhedetar village resort
483         bauwa hotel and guest house
485                     Edu Consultancy
486                          himal sign
487        unique art and sticker house
488      lulu media publication pvt ltd
489                        hotel icchya
490                         TMA travels
491                  global IT solution
492                           mini mart
493                              clinic
495               Jagdamba Depo & Sales
496                cosmetic and fitness
497                                 NaN
499                          handicraft
501                          sunglasses
504                          restaurant
505                         restaurant
506                                 NaN
507                Advertising buisness
508              distribution suppliers
510                         handicrafts

                                        Response Telecom
1                  not interested in advertising     NTC
2                          must contact in viber     NTC
3                want to start the advertisement     NTC
4            number not available 9th april 3:00     NTC
6                     not recieve call 9th april     NTC
7                              call not recieved     NTC
10           requested for customer number basis     NTC
12                             need to follow up     NTC
13                                 not reachable     NTC
14                                           NaN     NTC
15              more interested and visit office     NTC
16                     intereseted and call soon     NTC
17                          call when he is free     NTC
18                      call us when he is ready     NTC
19                             need to follow up     NTC
21                               need follow up      NTC
22                                           NaN     NTC
23                                        visit      NTC
24        interested and promise to visit office     NTC
25                               promise a visit     NTC
26        interested and provide time when ready     NTC
27   Need to boost the facebook page immediately     NTC
28                                           NaN     NTC
29           call not recieved (22th april 3 pm)     NTC
30                   need to follow up tommorrow     NTC
32                               tommorrow 11 am     NTC
33                         come office afternoon     NTC
34                      need follow up tommorrow     NTC
36                         need to send proposal     NTC
37                            cal he he is freee     NTC
..                                           ...     ...
469                                 switched off     NTC
470                    need to call after 1 week     NTC
475                        need to send proposal     NTC
476                        Call by himself later     NTC
477                                call tomorrow     NTC
478                        Call by himself later     NTC
479                                 not received     NTC
480                        Call by himself later     NTC
482                        Call by himself later     NTC
483                                 not received     NTC
485                                    Converted     NTC
486                                after 28 gate     NTC
487                                after4-5 days     NTC
488                        Call by himself later     NTC
489                               not interested     NTC
490                                 he will call     NTC
491                      sent proposal/follow up     NTC
492                                   follow up      NTC
493                                    follow up     NTC
495                      sent proposal/follow up     NTC
496                                 he will call     NTC
497                               not interested     NTC
499                               not interested     NTC
501                                   will visit     NTC
504              need to send proposal/follow up     NTC
505                                 he will call     NTC
506                                   call later     NTC
507                      sent proposal/follow up     NTC
508                         he will inform later     NTC
510                               he will visit      NTC

[313 rows x 5 columns]